name: responsive_text_example
description: Example app for responsive_text package
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"  # Lowered from >=3.4.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_text_plus:
    path: ../
publish_to: none

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
