name: responsive_text
description: "ResponsiveText is a versatile Flutter widget for responsive text scaling, offering customizable font size adaptation based on screen dimensions, perfect for enhancing text readability across devices."
version: 1.0.3
homepage: https://github.com/muhammednajeebay/responsive_text?tab=readme-ov-file#readme
repository: https://github.com/muhammednajeebay/responsive_text
topics: [responsive, text, scaling, ui, flutter]
documentation: https://pub.dev/documentation/responsive_text/latest/

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
# flutter:
#   plugin:
#     platforms:
#       android:
#         pluginClass: ResponsiveTextPlugin
#       ios:
#         pluginClass: ResponsiveTextPlugin
#       web:
#         pluginClass: ResponsiveTextWeb
#         fileName: responsive_text_web.dart
#       linux:
#         pluginClass: ResponsiveTextPlugin
#       macos:
#         pluginClass: ResponsiveTextPlugin
#       windows:
#         pluginClass: ResponsiveTextPlugin

