name: responsive_text_plus
description: "A customizable text widget that dynamically scales its font size based on screen size or container dimensions, ensuring legibility across devices."
version: 1.0.3
homepage: https://github.com/muhammednajeebay/responsive_text
documentation: https://muhammednajeebay.github.io/responsive_text/
repository: https://github.com/muhammednajeebay/responsive_text
Author: Muhammed Najeeb AY
author_url: https://najeebay.netlify.app/

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
