name: responsive_text
description: "ResponsiveText is a versatile Flutter widget for responsive text scaling, offering customizable font size adaptation based on screen dimensions, perfect for enhancing text readability across devices."
version: 1.0.0
homepage: https://github.com/muhammednajeebay/responsive_text
repository: https://github.com/muhammednajeebay/responsive_text
topics: [responsive, text, scaling, ui, flutter]

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
